on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: Build

jobs:
  build-xelatex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk main.tex -halt-on-error -time -xelatex
        name: build with XeLaTeX
      - uses: actions/upload-artifact@v4
        with:
          path: main.pdf
          name: build-xelatex
        name: upload build artifacts
  build-lualatex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk main.tex -halt-on-error -time -lualatex
        name: build with LuaLaTeX
      - uses: actions/upload-artifact@v4
        with:
          path: main.pdf
          name: build-lualatex
        name: upload build artifacts
