on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

jobs:
  release-xelatex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            latexmk main.tex -halt-on-error -time -xelatex
        name: build with XeLaTeX
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: "New release ${{ github.ref }}"
          draft: true
          prerelease: false
          files: |
            main.pdf
